import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Blogger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ marginBlockStart: '5rem'}}>
        <div>
          <h1>Home Page</h1>
        </div>
      </main>
    </>
  )
}
